# Generated by Django 2.1.1 on 2019-05-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190524_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='mark',
            new_name='student_mark',
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
