# Generated by Django 2.1.1 on 2019-05-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190524_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='student_mark',
            field=models.FloatField(),
        ),
    ]
