# Generated by Django 2.1.1 on 2019-05-25 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190524_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='subjects',
            new_name='subject',
        ),
    ]
