# Generated by Django 2.1.1 on 2019-05-25 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190525_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subject',
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Subject'),
            preserve_default=False,
        ),
    ]
