# Generated by Django 2.1.1 on 2019-05-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_subject_in_total_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='student',
        ),
        migrations.AddField(
            model_name='subject',
            name='student_seat_number',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
